name: web_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  responsive_framework: ^0.2.0
  font_awesome_flutter: ^10.5.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^4.2.1  # Added version
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  visibility_detector: ^0.4.0+2
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Added for better code analysis

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cv/
    - assets/ESH_image/  # Fixed typo (space removed)
    - assets/UltraRays_image/
    - assets/UltraRays_Business/
    - assets/cv/Darshan_Zalavadiya_Resume.pdf